// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7Qz89xnqXqdWCqeLfp63vj
// Component: 6F13kKZhV-nj
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Card from "../../Card"; // plasmic-import: hX3LMAo3k5Ox/component
import Button from "../../Button"; // plasmic-import: cMoejsjYHZAF/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { useScreenVariants as useScreenVariantsljhxFWaBdn0 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _ljhxFWaBDN0/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 7Qz89xnqXqdWCqeLfp63vj/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: 6F13kKZhV-nj/css
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: Y2slRN9kNB91/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: Ib5Bys4otdPF/icon

createPlasmicElementProxy;

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

const $$ = {};

function PlasmicHome__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,
        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsljhxFWaBdn0()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__wnvFg)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bgJu)}
            >
              <Card
                children={null}
                className={classNames("__wab_instance", sty.card__jCOk)}
                title={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__wDYy)}
                    displayHeight={"53px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"216px"}
                    loading={"lazy"}
                    src={
                      "https://s3.olitt.com/media/3f827326-1d62-4817-a1fe-55924c72a2a2-Collage_2023-12-09_10_45_51.jpg"
                    }
                  />
                }
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qpSj)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__lxU8A)}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fiTue)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__ana9I)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__my2Z8)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___6Kt4C)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hkRCz
                      )}
                    >
                      {"HOME"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__zIeE9)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__lmCC)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__eUhim)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qfr8
                      )}
                    >
                      {"ABOUT"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__fbHlh)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg___0Uq0N)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___2Vdh2)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___398PE
                      )}
                    >
                      {"MENU"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__nElWz)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__tzRft)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__huQiP)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cXZx
                      )}
                    >
                      {"GALLERY"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__znOcB)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__hH0Ge)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__tQUxy)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vzM9
                      )}
                    >
                      {"CONTACT US"}
                    </div>
                  </Button>
                </Stack__>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qT7N)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button__ykHLb
                      )}
                    >
                      {"Sign up"}
                    </button>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__cjCon
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon4Icon
                          className={classNames(projectcss.all, sty.svg__x1PfB)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <CheckSvgIcon
                          className={classNames(projectcss.all, sty.svg__u3QgH)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sBp9Z
                        )}
                      >
                        {"Log in"}
                      </div>
                    </Button>
                  </div>
                ) : null}
              </Stack__>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox___53Psr)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fyVo
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Our customers love us! Read what they have to say below."}
                  </span>
                </React.Fragment>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___4QWdd)}>
              <div className={classNames(projectcss.all, sty.columns__bzg9R)}>
                <div className={classNames(projectcss.all, sty.column__n9Jfu)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f2SZc
                    )}
                  >
                    {
                      "So happy with my stash from Quench. Delivered fresh and so good. Only problem is it's addictive.\n"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__wJrl)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rLjw7
                    )}
                  >
                    {
                      "The Fruit Punch Lemonade was a winner and so was the liquorice milkshake. Difficult to choose which was better to be honest.\n\n"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__opqA3)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__owZhc
                    )}
                  >
                    {
                      "The immune boosting shots are absolutely divine!!! Jazakallah for the amazing service and top quality products.\n"
                    }
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__jSgIh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jvov
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#000000", fontWeight: 900 }}
                  >
                    {"ABOUT QUENCH"}
                  </span>
                  <React.Fragment>{"\n"}</React.Fragment>
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wqGw0
                )}
              >
                {
                  'With a vision of a Juice Bar in 2022, but no manpower or funding to kick-start this fresh dream, and not quite ready to quit, a new home industry started. Initially, I started with a handful of freshly blended juice flavors, and now two years later, Quench is an "Indulge Your Tastebuds" experience made from the finest ingredients. Our menu is suited around the entire family, preservative free and of a delectable variety of juices, wellness shots, indulgent shakes, popsicles, snack boxes and dipping sauces. We cater for corporate events, parties and seasonal gifting with personalized labels at no extra cost.\n'
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__ceWgA)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ybA8
                )}
              >
                {"MENU\n"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rkaEc
                )}
              >
                {
                  'Quench is an "Indulge Your Tastebuds" experience made with the finest ingredients.'
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cxYg
                )}
              >
                {
                  "Storage Instructions: 3 days in the fridge. 3 months in the freezer.\nClick on the MENU link to view our detailed range.\n"
                }
              </div>
              <Button
                className={classNames("__wab_instance", sty.button___0Fv5G)}
                color={"green"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lLBeb
                  )}
                >
                  {"MENU"}
                </div>
              </Button>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__d7WUx
              )}
            >
              {""}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hQzj
              )}
            >
              {""}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4I7Hu
              )}
            >
              {""}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__oLk1V)}>
              <div className={classNames(projectcss.all, sty.columns__bSlV)}>
                <div className={classNames(projectcss.all, sty.column___8PwF2)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mppcG)}
                    displayHeight={"374px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      "https://s3.olitt.com/media/62f373da-eed2-4d1f-b9a8-2f76343b7021-20240119_142434.jpg"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0PLUr
                    )}
                  >
                    {"FRESHLY BLENDED\n"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2Fv1S
                    )}
                  >
                    {"Fresh Juices"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cmYpo
                    )}
                  >
                    {
                      "A selection of the finest fruits are blended and squeezed to create delicious, delectable flavors. All Juices are preservative free.\n\n"
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6L4IM
                    )}
                  >
                    {""}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__bYabp)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__keAtm)}
                    displayHeight={"374px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      "https://s3.olitt.com/media/62f373da-eed2-4d1f-b9a8-2f76343b7021-20240119_142434.jpg"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z2Km5
                    )}
                  >
                    {"COLD PRESSED\n"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ietgD
                    )}
                  >
                    {"Wellness Shots"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pXdY
                    )}
                  >
                    {
                      "A very concentrated range of cold pressed fruits of exceptional quality that encourage the immune system and overall health. All Cold Pressed Wellness Shots are Preservative Free."
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dAcY
                    )}
                  >
                    {""}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__lFsU)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__dxowZ)}
                    displayHeight={"374px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      "https://s3.olitt.com/media/62f373da-eed2-4d1f-b9a8-2f76343b7021-20240119_142434.jpg"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vdw8S
                    )}
                  >
                    {"FRESH JUICE POUCHES\n"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__whgng
                    )}
                  >
                    {"Lunch Bag Treats"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qkun2
                    )}
                  >
                    {
                      "A range especially suited to kids as it is fresh, healthy and preservative free. Store your pack of juice pouches in the freezer and pop one into lunch bags resulting in a 'ready to drink' by lunch break. These are great for kids parties and play dates as well.\n"
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kEb1Q
                    )}
                  >
                    {""}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__sDn8A)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__okKhM)}
                    displayHeight={"374px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      "https://s3.olitt.com/media/62f373da-eed2-4d1f-b9a8-2f76343b7021-20240119_142434.jpg"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yRgJz
                    )}
                  >
                    {"GOURMET MOCKTAILS\n"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__or9Bn
                    )}
                  >
                    {"Handcrafted Gourmet Fusions"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3E75K
                    )}
                  >
                    {
                      "A collaboration of exclusive, sophisticated flavors to intrigue your palette. Share over a dinner table from a 660ml glass bottle or the 330ml individual serving."
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8V2BV
                    )}
                  >
                    {""}
                  </div>
                </div>
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uJuzY
              )}
            >
              {"GALLERY\n"}
            </div>
            <div className={classNames(projectcss.all, sty.columns__jI0FX)}>
              <div className={classNames(projectcss.all, sty.column__c49Tc)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__pt97X)}
                  displayHeight={"374px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/22296b1d-8650-4547-bed0-12a8eb35cce5-Screenshot_20240711_093708_Instagram.jpg"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jWPyd
                  )}
                >
                  {""}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__izXl)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___3Uc0E)}
                  displayHeight={"396px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"452px"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/8aa8ac3f-81f5-4d62-b8f0-bbb775bff19e-MOCKTAIL_INTRO.jpg"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___9OQdB)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__j0Wqk)}
                  displayHeight={"374px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/2b6eb3eb-0e40-43d9-9205-13d488059173-IMG_20240604_154405_539.webp"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__bmC5Y)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__wN9H)}
                  displayHeight={"374px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/32d662e3-f8b8-4030-a2ae-5d4914d3f059-Screenshot_20240711_095854_Instagram.jpg"
                  }
                />
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__mkger)}>
              <div className={classNames(projectcss.all, sty.column__tVwvg)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__xcgBx)}
                  displayHeight={"374px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/32d29304-90d6-4b23-a553-fdd14b9e7f78-20240313_145801.jpg"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cN7Vc
                  )}
                >
                  {""}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__uu1Ab)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__wJjQh)}
                  displayHeight={"396px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"452px"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/62247eca-91c2-4c2a-849d-feb9bc7ffe13-20240326_111141.jpg"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___4LRhp)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__znOyF)}
                  displayHeight={"374px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/2c7fe5bd-de18-4cca-8e19-3b216ac3dd2b-Screenshot_20240711_093856_Instagram.jpg"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hJ9Xf)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__pg0Pj)}
                  displayHeight={"374px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/439dc4ae-0363-46e9-b409-a7ca3572b663-IMG_20240625_212707_284.webp"
                  }
                />
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__uvGcr)}>
              <div className={classNames(projectcss.all, sty.column__cJGob)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mnerr)}
                  displayHeight={"374px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://s3.olitt.com/media/b761f951-68f0-4675-a225-3088c0ec10b8-IMG_20240626_115359_257.webp"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___0Alp)} />
              <div className={classNames(projectcss.all, sty.column__xtD10)} />
              <div className={classNames(projectcss.all, sty.column__tok9W)} />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__mgQgH)}>
              <div className={classNames(projectcss.all, sty.columns__kJBpm)}>
                <div className={classNames(projectcss.all, sty.column__quqCz)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ptn9F
                    )}
                  >
                    {"Visit our Gallery\n"}
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___2ZDiM)}
                    color={"green"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Oil2
                      )}
                    >
                      {"Gallery"}
                    </div>
                  </Button>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wtgpS
                    )}
                  >
                    {"\nSTOCKIST & CONTACT US\n"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b4Ml1
                    )}
                  >
                    {"Click Here for a list of Quench Stockist"}
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___6FMf)}
                    color={"green"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cWmYs
                      )}
                    >
                      {"Contact"}
                    </div>
                  </Button>
                </div>
                <div
                  className={classNames(projectcss.all, sty.column__zwAs2)}
                />

                <div
                  className={classNames(projectcss.all, sty.column___0AUr9)}
                />
              </div>
            </div>
            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__mswJd)}>
                <Card
                  className={classNames("__wab_instance", sty.card__qWkoW)}
                  title={null}
                >
                  {(() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.form),
                      extendedOnValuesChange:
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["form", "value"],
                          FormWrapper_Helpers
                        ),
                      formItems: undefined,
                      labelCol: { span: 8, horizontalOnly: true },
                      layout: "vertical",
                      mode: undefined,
                      onIsSubmittingChange:
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "isSubmitting",
                          ["form", "isSubmitting"],
                          FormWrapper_Helpers
                        ),
                      ref: ref => {
                        $refs["form"] = ref;
                      },
                      wrapperCol: { span: 16, horizontalOnly: true }
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "form.value"
                        },
                        {
                          name: "isSubmitting",
                          plasmicStateName: "form.isSubmitting"
                        }
                      ],

                      [],
                      FormWrapper_Helpers ?? {},
                      child$Props
                    );
                    return (
                      <FormWrapper
                        data-plasmic-name={"form"}
                        data-plasmic-override={overrides.form}
                        {...child$Props}
                      >
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__h5IoD
                          )}
                          label={"Name"}
                          name={"name"}
                        >
                          <AntdInput
                            className={classNames("__wab_instance", sty.input)}
                          />
                        </FormItemWrapper>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__i2MTx
                          )}
                          label={"Message"}
                          name={"message"}
                        >
                          <AntdTextArea
                            className={classNames(
                              "__wab_instance",
                              sty.textArea
                            )}
                          />
                        </FormItemWrapper>
                        <AntdButton
                          className={classNames(
                            "__wab_instance",
                            sty.button__u0Pjw
                          )}
                          submitsForm={true}
                          type={"primary"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__svk00
                            )}
                          >
                            {"SEND"}
                          </div>
                        </AntdButton>
                      </FormWrapper>
                    );
                  })()}
                </Card>
              </div>
            </section>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__uvrcy)}
            >
              <div className={classNames(projectcss.all, sty.column__rAnG)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__kxh8P)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__id0XI
                    )}
                  >
                    {"menu LINKS"}
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__nu8Q7)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__ppR3A)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___1ZmN1)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__usLwp
                      )}
                    >
                      {"Home"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__ujuDr)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__ugzU)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__tkqd)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cPjaN
                      )}
                    >
                      {"About "}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__jXfS5)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__teaOs)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__cs4Bk)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___03GPv
                      )}
                    >
                      {"Menu"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__sExL)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg___60OGo)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__cd81)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qPei
                      )}
                    >
                      {"Gallery"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__emJc9)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__bmfG)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__k3RTx)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jUwvA
                      )}
                    >
                      {"Contact us"}
                    </div>
                  </Button>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column___053Tv)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tSyfx)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__and7
                    )}
                  >
                    {"Contact"}
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__vZxsr)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__tWeZm)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___2LeE5)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3KsjB
                      )}
                    >
                      {" Location"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__uEJ)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__rhOeg)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__reb4)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__j2MX
                      )}
                    >
                      {" zaquench@gmail.com"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__tUqjH)}
                    color={"clear"}
                    endIcon={
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__cKfhS)}
                        role={"img"}
                      />
                    }
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___6KzYu)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8Ojgc
                      )}
                    >
                      {" Call : +27 79 284 5879\n"}
                    </div>
                  </Button>
                </Stack__>
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__qRcZg)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mon1R
                )}
              >
                {"\u00a9 2023 All Rights Reserved"}
              </div>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "section", "form", "input", "textArea"],
  section: ["section", "form", "input", "textArea"],
  form: ["form", "input", "textArea"],
  input: ["input"],
  textArea: ["textArea"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    form: makeNodeComponent("form"),
    input: makeNodeComponent("input"),
    textArea: makeNodeComponent("textArea"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
